---
- name: Install dependencies
  apt:
    name: "{{ __asdf_dependencies }}"
    state: present
  become: true

- name: Clone repository
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"

- import_tasks: shell.yml

- name: Create configuration script
  template:
    src: asdfrc.j2
    dest: ~/.asdfrc
