---
- name: Install dependencies
  apt:
    name: git
    state: present
  become: true

- name: Clone repository
  git:
    repo: "{{ asdf_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"

- import_tasks: fish.yml
  when: ansible_user_shell == "/usr/bin/fish"

- name: Create configuration script
  template:
    src: asdfrc.j2
    dest: ~/.asdfrc
