---
- import_tasks: shell/bash.yml
  when: ansible_user_shell == "/bin/bash"

- import_tasks: shell/fish.yml
  when: ansible_user_shell == "/usr/bin/fish"

- import_tasks: shell/zsh.yml
  when: ansible_user_shell == "/bin/zsh"
